import Head from "next/head";

import Nav from "../components/user/Nav";
import Script from "next/script";

import { useRouter } from "next/router";

export default function Home({ data }) {
  return (
    <div className={"container"}>
      <Nav />
      <Head>
        <title>Aplikasi Fish Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello </h1>
        <h3>Daftar Ikan</h3>
        <div className="row">
          {data.map((item, index) => {
            return (
              <div
                key={index}
                className="card col-md-4 m-2"
                style={{ width: "15rem" }}
              >
                <div className="card-body">
                  <h5 className="card-title"> Ikan {item.nama}</h5>
                  <p className="card-text">Kualitas {item.kualitas}</p>
                  <p className="card-text">harga {item.harga}</p>
                  <p className="card-text">Ukuran {item.ukuran}</p>
                </div>
              </div>
            );
          })}
        </div>
      </main>

      <footer>
        <h4>Footer</h4>
      </footer>
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"
      ></Script>
    </div>
  );
}

export async function getServerSideProps({ query }) {
  const url = `http://localhost:5000/fish/`;
  //fetch data
  const res = await fetch(url);
  const data = await res.json();
  return { props: { data } };
}
